return {
	ensure_installed = {
		"lua-language-server",
		"pyright",
		"stylua",
		"typescript-language-server",
		"rust-analyzer",
		"gopls",
		"json-lsp",
		"bash-language-server",
		"clangd",
		"html-lsp",
		"css-lsp",
		"emmet-language-server",
		"clang-format",
		"prettier",
		"eslint_d",
		"tombi",
		"prettier",
		"autopep8",
		"gofumpt",
		"selene",
		"flake8",
		"cpplint",
		"golangci-lint",
	},
	max_concurrent_installers = 1,
}
