return {
	ensure_installed = {
		"lua-language-server",
		"pyright",
		"isort",
		"black",
		"stylua",
		"typescript-language-server",
		"rust-analyzer",
		"gopls",
		"json-lsp",
		"bash-language-server",
		"clangd",
		"html-lsp",
		"css-lsp",
		"emmet-language-server",
		"clang-format",
		"prettier",
		"eslint",
		"taml-language-server",
		"tombi",
	},
	max_concurrent_installers = 1,
}
