return {
-- 	{ "L3MON4D3/LuaSnip", keys = {} },
-- 	{
-- 		"saghen/blink.cmp",
-- 		dependencies = {
-- 			"rafamadriz/friendly-snippets",
-- 		},
-- 		version = "1.*",
-- 		config = function()
-- 			vim.opt.completeopt = { "menu", "menuone", "noselect" }
-- 			require("blink.cmp").setup({
-- 				snippets = { preset = "luasnip" },
-- 				signature = { enabled = true },
-- 				appearance = {
-- 					use_nvim_cmp_as_default = false,
-- 					nerd_font_variant = "normal",
-- 					kind_icons = {
-- 						Text = "",
-- 						Method = "",
-- 						Function = "󰊕",
-- 						Constructor = "",
-- 						Field = "",
-- 						Variable = "󰀫",
-- 						Class = "",
-- 						Interface = "",
-- 						Module = "",
-- 						Property = "",
-- 						Unit = "",
-- 						Value = "",
-- 						Enum = "",
-- 						Keyword = "",
-- 						Snippet = "",
-- 						Color = "",
-- 						File = "",
-- 						Reference = "",
-- 						Folder = "",
-- 						EnumMember = "",
-- 						Constant = "",
-- 						Struct = "",
-- 						Event = "",
-- 						Operator = "",
-- 						TypeParameter = "",
-- 					},
-- 				},
-- 				sources = {
-- 					default = { "lsp", "path", "snippets", "buffer" },
-- 					providers = {
-- 						cmdline = {
-- 							min_keyword_length = 2,
-- 						},
-- 					},
-- 				},
-- 				keymap = {
-- 					preset = "none", -- desactiva todos los presets por defecto
--
-- 					-- Mostrar completado o cerrarlo
-- 					["<C-a>"] = { "show", "hide" },
--
-- 					-- Aceptar sugerencia solo si hay una seleccionada
-- 					["<CR>"] = { "accept", "fallback" },
--
-- 					-- TAB: avanzar snippet o seleccionar siguiente
-- 					["<Tab>"] = { "snippet_forward", "select_next", "fallback" },
--
-- 					-- Shift+TAB: retroceder snippet o seleccionar anterior
-- 					["<S-Tab>"] = { "snippet_backward", "select_prev", "fallback" },
--
-- 					-- Navegación por ítems
-- 					["<Up>"] = { "select_prev", "fallback" },
-- 					["<Down>"] = { "select_next", "fallback" },
-- 					["<C-p>"] = { "select_prev", "fallback_to_mappings" },
-- 					["<C-n>"] = { "select_next", "fallback_to_mappings" },
--
-- 					-- Scroll en documentación flotante
-- 					["<C-t>"] = { "scroll_documentation_up", "fallback" },
-- 					["<C-g>"] = { "scroll_documentation_down", "fallback" },
--
-- 					-- Mostrar documentación y alternar
-- 					["<C-Space>"] = { "show", "show_documentation", "hide_documentation" },
-- 					["<C-e>"] = { "hide", "fallback" },
--
-- 					-- Mostrar firma de función
-- 					["<C-k>"] = { "show_signature", "hide_signature", "fallback" },
-- 				},
-- 				cmdline = {
-- 					enabled = false,
-- 					completion = { menu = { auto_show = true } },
-- 					keymap = {
-- 						["<CR>"] = { "accept_and_enter", "fallback" },
-- 					},
-- 				},
-- 				completion = {
-- 					menu = {
-- 						border = nil,
-- 						scrolloff = 1,
-- 						scrollbar = false,
-- 						draw = {
-- 							columns = {
-- 								{ "kind_icon" },
-- 								{ "label", "label_description", gap = 1 },
-- 								{ "kind" },
-- 								{ "source_name" },
-- 							},
-- 						},
-- 					},
-- 					documentation = {
-- 						window = {
-- 							border = nil,
-- 							scrollbar = false,
-- 							winhighlight = "Normal:BlinkCmpDoc,FloatBorder:BlinkCmpDocBorder,EndOfBuffer:BlinkCmpDoc",
-- 						},
-- 						auto_show = true,
-- 						auto_show_delay_ms = 500,
-- 					},
-- 				},
-- 			})
--
-- 			require("luasnip.loaders.from_vscode").lazy_load()
-- 		end,
-- 	},
}
