return {
    "nvim-treesitter/nvim-treesitter",
    branch = "master",
    lazy = false,
    build = ":TSUpdate",
    dependencies = {
        "nvim-treesitter/nvim-treesitter-textobjects",
    },
    opts = {
        ensure_installed = {
            "vim",
            "vimdoc",
            "lua",
            "python",
            "c",
            "cpp",
            "javascript",
            "typescript",
            "json",
            "bash",
            "rust",
            "go",
            "markdown",
            "yaml",
            "toml",
            "html",
            "css",
            "cmake",
        },
        highlight = {
            enable = true,
        },
        sync_install = false,
        auto_install = true,
        additional_vim_regex_highlighting = false,
        textobjects = {
            select = {
                enable = true,
                lookahead = true,
                keymaps = {
                    ["af"] = "@function.outer",
                    ["if"] = "@function.inner",
                    ["ac"] = "@class.outer",
                    ["ic"] = "@class.inner",
                    ["as"] = "@local.scope",
                    ["ca"] = "@conditional.outer",
                    ["ci"] = "@conditional.inner",
                    ["al"] = "@loop.outer",
                    ["il"] = "@loop.inner",
                },
            },
        },
    },
}
